(defvar backup-dir "~/.emacs.d/backups/")
(setq backup-directory-alist (list (cons "." backup-dir)))
(setq-default indent-tabs-mode nil)
(setq tab-width 4)
(setq c-basic-offset tab-width)
(setq cperl-indent-level tab-width)
(when (version<= "26.0.50" emacs-version )
  (global-display-line-numbers-mode))
(setq column-number-mode t)
(when (version<= "23.0.0" emacs-version )
  (global-whitespace-mode))
(speedbar)
(when (version<= "27.0.0" emacs-version )
  (global-display-fill-column-indicator-mode))
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
;(require 'auto-complete)
;(global-auto-complete-mode t)
;(require 'company)
;(add-hook 'global-init-hook 'global-company-mode)
;(add-to-list 'company-backends 'company-c-headers)
